type FakeFetchParams = {
  url: string;
  delay: number;
};

const data = [
  {
    email: "melany.wijngaard@example.com",
    gender: "female",
    phone_number: "(727)-033-9347",
    birthdate: 608022796,
    location: {
      street: "2431 predikherenkerkhof",
      city: "staphorst",
      state: "gelderland",
      postcode: 64265,
    },
    username: "bigpeacock217",
    password: "eagle",
    first_name: "melany",
    last_name: "wijngaard",
    title: "miss",
    picture: "women/70.jpg",
  },
  {
    email: "nanna.pedersen@example.com",
    gender: "female",
    phone_number: "43672992",
    birthdate: 591428535,
    location: {
      street: "2177 fåborgvej",
      city: "aarhus",
      state: "syddanmark",
      postcode: 87547,
    },
    username: "purpleduck599",
    password: "davids",
    first_name: "nanna",
    last_name: "pedersen",
    title: "ms",
    picture: "women/68.jpg",
  },
  {
    email: "amelia.mercier@example.com",
    gender: "female",
    phone_number: "(168)-747-5950",
    birthdate: 1132298571,
    location: {
      street: "7454 rue duquesne",
      city: "echandens-denges",
      state: "vaud",
      postcode: 3811,
    },
    username: "whitefrog218",
    password: "forest",
    first_name: "amelia",
    last_name: "mercier",
    title: "madame",
    picture: "women/91.jpg",
  },
  {
    email: "sarah.oliver@example.com",
    gender: "female",
    phone_number: "0761-814-654",
    birthdate: 1038915780,
    location: {
      street: "3503 manor road",
      city: "manchester",
      state: "highlands and islands",
      postcode: "I30 5ZF",
    },
    username: "purplebear893",
    password: "boat",
    first_name: "sarah",
    last_name: "oliver",
    title: "ms",
    picture: "women/73.jpg",
  },
  {
    email: "عسل.مرادی@example.com",
    gender: "female",
    phone_number: "0925-326-2063",
    birthdate: 417058382,
    location: {
      street: "4981 شهید بهشتی",
      city: "پاکدشت",
      state: "مرکزی",
      postcode: 68555,
    },
    username: "ticklishfish813",
    password: "zaq12wsx",
    first_name: "عسل",
    last_name: "مرادی",
    title: "mrs",
    picture: "women/65.jpg",
  },
  {
    email: "özkan.tekelioğlu@example.com",
    gender: "male",
    phone_number: "(074)-376-7384",
    birthdate: 616226885,
    location: {
      street: "2260 anafartalar cd",
      city: "afyonkarahisar",
      state: "amasya",
      postcode: 31532,
    },
    username: "organiccat298",
    password: "coventry",
    first_name: "özkan",
    last_name: "tekelioğlu",
    title: "mr",
    picture: "men/69.jpg",
  },
  {
    email: "angela.newman@example.com",
    gender: "female",
    phone_number: "081-718-3989",
    birthdate: 479824115,
    location: {
      street: "3159 west street",
      city: "celbridge",
      state: "colorado",
      postcode: 82776,
    },
    username: "smallgorilla567",
    password: "1234567",
    first_name: "angela",
    last_name: "newman",
    title: "mrs",
    picture: "women/82.jpg",
  },
  {
    email: "buse.dağdaş@example.com",
    gender: "female",
    phone_number: "(855)-841-4810",
    birthdate: 1316736697,
    location: {
      street: "6428 anafartalar cd",
      city: "malatya",
      state: "mardin",
      postcode: 28227,
    },
    username: "crazypeacock394",
    password: "paulie",
    first_name: "buse",
    last_name: "dağdaş",
    title: "ms",
    picture: "women/14.jpg",
  },
  {
    email: "judith.schmitz@example.com",
    gender: "female",
    phone_number: "0171-7824648",
    birthdate: 1348121292,
    location: {
      street: "8227 römerstraße",
      city: "mittweida",
      state: "berlin",
      postcode: 34006,
    },
    username: "smallcat785",
    password: "prissy",
    first_name: "judith",
    last_name: "schmitz",
    title: "miss",
    picture: "women/49.jpg",
  },
  {
    email: "hector.guerrero@example.com",
    gender: "male",
    phone_number: "696-963-949",
    birthdate: 1040720948,
    location: {
      street: "5140 calle nebrija",
      city: "alcobendas",
      state: "navarra",
      postcode: 56387,
    },
    username: "lazyleopard999",
    password: "godfather",
    first_name: "hector",
    last_name: "guerrero",
    title: "mr",
    picture: "men/11.jpg",
  },
  {
    email: "carsta.rocha@example.com",
    gender: "male",
    phone_number: "(60) 1416-4953",
    birthdate: 296641611,
    location: {
      street: "2609 rua rio de janeiro ",
      city: "arapongas",
      state: "amapá",
      postcode: 91540,
    },
    username: "redfish833",
    password: "soccer12",
    first_name: "carsta",
    last_name: "rocha",
    title: "mr",
    picture: "men/4.jpg",
  },
  {
    email: "irene.morales@example.com",
    gender: "female",
    phone_number: "625-790-958",
    birthdate: 513983644,
    location: {
      street: "4096 calle del arenal",
      city: "lorca",
      state: "castilla y león",
      postcode: 40542,
    },
    username: "goldenfish109",
    password: "field",
    first_name: "irene",
    last_name: "morales",
    title: "mrs",
    picture: "women/87.jpg",
  },
  {
    email: "laly.dasilva@example.com",
    gender: "female",
    phone_number: "(082)-419-9335",
    birthdate: 1123776172,
    location: {
      street: "5396 rue duquesne",
      city: "villars-le-terroir",
      state: "ticino",
      postcode: 9152,
    },
    username: "bluebird274",
    password: "design",
    first_name: "laly",
    last_name: "da silva",
    title: "mademoiselle",
    picture: "women/9.jpg",
  },
  {
    email: "benjamin.patel@example.com",
    gender: "male",
    phone_number: "(788)-424-7144",
    birthdate: 929834606,
    location: {
      street: "3675 tennyson street",
      city: "masterton",
      state: "manawatu-wanganui",
      postcode: 81684,
    },
    username: "beautifulbear427",
    password: "cartman",
    first_name: "benjamin",
    last_name: "patel",
    title: "mr",
    picture: "men/40.jpg",
  },
  {
    email: "noah.poulsen@example.com",
    gender: "male",
    phone_number: "53705244",
    birthdate: 1314124015,
    location: {
      street: "7998 oddenvej",
      city: "nr åby",
      state: "syddanmark",
      postcode: 73617,
    },
    username: "purplesnake503",
    password: "zelda",
    first_name: "noah",
    last_name: "poulsen",
    title: "mr",
    picture: "men/41.jpg",
  },
  {
    email: "jeffrey.myers@example.com",
    gender: "male",
    phone_number: "(449)-485-5688",
    birthdate: 567993820,
    location: {
      street: "8239 pockrus page rd",
      city: "tulsa",
      state: "colorado",
      postcode: 47392,
    },
    username: "greenswan192",
    password: "karate",
    first_name: "jeffrey",
    last_name: "myers",
    title: "mr",
    picture: "men/83.jpg",
  },
  {
    email: "noélie.roux@example.com",
    gender: "female",
    phone_number: "06-68-19-42-68",
    birthdate: 669873438,
    location: {
      street: "6224 rue barrème",
      city: "paris",
      state: "ain",
      postcode: 89564,
    },
    username: "blueelephant373",
    password: "282828",
    first_name: "noélie",
    last_name: "roux",
    title: "mrs",
    picture: "women/51.jpg",
  },
  {
    email: "jake.brown@example.com",
    gender: "male",
    phone_number: "(427)-211-8595",
    birthdate: 341267763,
    location: {
      street: "9499 lake road",
      city: "nelson",
      state: "otago",
      postcode: 90556,
    },
    username: "brownbear342",
    password: "ramones",
    first_name: "jake",
    last_name: "brown",
    title: "mr",
    picture: "men/94.jpg",
  },
  {
    email: "abigail.hamilton@example.com",
    gender: "female",
    phone_number: "081-273-7886",
    birthdate: 870815573,
    location: {
      street: "4622 green lane",
      city: "swords",
      state: "idaho",
      postcode: 77531,
    },
    username: "smallswan192",
    password: "google",
    first_name: "abigail",
    last_name: "hamilton",
    title: "mrs",
    picture: "women/46.jpg",
  },
  {
    email: "abssilão.rodrigues@example.com",
    gender: "male",
    phone_number: "(12) 1563-0822",
    birthdate: 12543906,
    location: {
      street: "2358 rua são luiz ",
      city: "pinhais",
      state: "amapá",
      postcode: 62771,
    },
    username: "smallleopard973",
    password: "emerson",
    first_name: "abssilão",
    last_name: "rodrigues",
    title: "mr",
    picture: "men/5.jpg",
  },
  {
    email: "sofia.sales@example.com",
    gender: "female",
    phone_number: "(69) 6275-4624",
    birthdate: 841700488,
    location: {
      street: "3688 rua joão xxiii",
      city: "catanduva",
      state: "piauí",
      postcode: 26830,
    },
    username: "redlion952",
    password: "kaiser",
    first_name: "sofia",
    last_name: "sales",
    title: "ms",
    picture: "women/66.jpg",
  },
  {
    email: "jeremy.weiss@example.com",
    gender: "male",
    phone_number: "0172-9704083",
    birthdate: 1097265312,
    location: {
      street: "3704 ringstraße",
      city: "lüchow-dannenberg",
      state: "bremen",
      postcode: 10531,
    },
    username: "blackbird279",
    password: "mone",
    first_name: "jeremy",
    last_name: "weiss",
    title: "mr",
    picture: "men/37.jpg",
  },
  {
    email: "joan.vega@example.com",
    gender: "male",
    phone_number: "603-901-577",
    birthdate: 1056841988,
    location: {
      street: "7526 calle de la democracia",
      city: "torrejón de ardoz",
      state: "navarra",
      postcode: 93823,
    },
    username: "lazypanda981",
    password: "asia",
    first_name: "joan",
    last_name: "vega",
    title: "mr",
    picture: "men/74.jpg",
  },
  {
    email: "phillip.torres@example.com",
    gender: "male",
    phone_number: "(323)-188-2019",
    birthdate: 401173794,
    location: {
      street: "5990 hillcrest rd",
      city: "toledo",
      state: "louisiana",
      postcode: 92625,
    },
    username: "ticklishtiger122",
    password: "jupiter",
    first_name: "phillip",
    last_name: "torres",
    title: "mr",
    picture: "men/64.jpg",
  },
  {
    email: "dora.barnes@example.com",
    gender: "female",
    phone_number: "0410-268-463",
    birthdate: 891949738,
    location: {
      street: "4899 brown terrace",
      city: "devonport",
      state: "queensland",
      postcode: 2861,
    },
    username: "purplebird909",
    password: "sally",
    first_name: "dora",
    last_name: "barnes",
    title: "miss",
    picture: "women/40.jpg",
  },
  {
    email: "julie.cole@example.com",
    gender: "female",
    phone_number: "0790-578-725",
    birthdate: 734058466,
    location: {
      street: "7742 king street",
      city: "stoke-on-trent",
      state: "isle of wight",
      postcode: "DC00 3ZH",
    },
    username: "browngoose690",
    password: "100000",
    first_name: "julie",
    last_name: "cole",
    title: "mrs",
    picture: "women/42.jpg",
  },
];

export const fakeFetch = ({ url, delay }: FakeFetchParams): Promise<any> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const response = data;
      resolve(response);
    }, delay);
  });
};
